name: CI/CD with Minikube on Contabo

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy to Contabo Minikube
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          script: |
            cd /root/devops_project  # Your project path on Contabo server

            # Use minikube's Docker environment
            eval $(minikube -p minikube docker-env)

            # Build docker image inside minikube docker
            docker build -t my-static-site:latest .

            # Deploy or update Kubernetes app
            kubectl apply -f deployment.yaml

            # Wait until deployment rolls out
            kubectl rollout status deployment/static-site
