name: Deploy to Minikube on Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Contabo and deploy on Minikube
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          script: |
            # Ensure Minikube is running
            minikube status || minikube start

            # Switch Docker to Minikube's daemon
            eval $(minikube docker-env)

            # Prepare working directory
            mkdir -p /home/${USER}/static-deploy
            cd /home/${USER}/static-deploy

            # Clean previous files
            rm -f index.html Dockerfile

            # Save the latest index.html from the repo
            echo "${{ secrets.INDEX_HTML }}" > index.html

            # Create Dockerfile
            cat <<EOF > Dockerfile
            FROM python:3.11-alpine
            WORKDIR /app
            COPY index.html /app/
            EXPOSE 8081
            CMD ["python3", "-m", "http.server", "8081"]
            EOF

            # Build Docker image in Minikube
            docker build -t static-site-image:latest .

            # Create Kubernetes deployment YAML
            cat <<EOF > deployment.yaml
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: static-site
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: static-site
              template:
                metadata:
                  labels:
                    app: static-site
                spec:
                  containers:
                    - name: static-site
                      image: static-site-image:latest
                      ports:
                        - containerPort: 8081
            EOF

            # Create service YAML
            cat <<EOF > service.yaml
            apiVersion: v1
            kind: Service
            metadata:
              name: static-site-service
            spec:
              type: NodePort
              selector:
                app: static-site
              ports:
                - port: 8081
                  targetPort: 8081
                  nodePort: 30081
            EOF

            # Apply deployment and service
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
