name: Deploy Static HTML using Python HTTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Contabo with Python HTTP Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH and deploy on Contabo using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          password: ${{ secrets.CONTABO_PASSWORD }}
          script: |
            cd /root/devops_project

            # Stop and remove old container if exists
            docker stop static-site || true
            docker rm static-site || true

            # Remove old image
            docker rmi static-site-image || true

            # Pull latest code
            rm -rf devops
            git clone https://github.com/riphah012/devops.git
            cd devops

            # Copy index.html to root project directory
            cp index.html /root/devops_project/

            # Create Dockerfile for Python HTTP server on port 3000
            cat <<EOF > Dockerfile
            FROM python:3.11-alpine
            WORKDIR /app
            COPY index.html /app/
            EXPOSE 3000
            CMD ["python3", "-m", "http.server", "3000"]
            EOF

            # Build Docker image
            docker build -t static-site-image .

            # Run Docker container and expose port 3000
            docker run -d --name static-site -p 3000:3000 static-site-image
